/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Immanity
 */
public class History_Panel extends javax.swing.JPanel {

    /**
     * Creates new form History
     */
    public History_Panel() {
        initComponents();
        displayFilm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        HistoryTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(38, 38, 38));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 50)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("History");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 750, -1));

        HistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Film Id", "Title", "Genre", "Duration", "Watch Plan", "Watch Date"
            }
        ));
        jScrollPane1.setViewportView(HistoryTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 700, -1));
    }// </editor-fold>//GEN-END:initComponents
    
    
    Connection Con = null;
    Statement St = null;
    ResultSet Rs = null;
    
    private void displayFilm() {
        try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cinehub", "root", "");
            St = Con.createStatement();
            Rs = St.executeQuery("select * from historyTable");
            HistoryTable.setModel(DbUtils.resultSetToTableModel(Rs));
        }catch (SQLException e){
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable HistoryTable;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
