/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Main.Film_Panel;


/**
 *
 * @author Immanity
 */
public class Main_Page extends javax.swing.JFrame {
    

    /**
     * Creates new form Main_Page
     */
    public Main_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SideBar = new javax.swing.JPanel();
        Home_Menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PlanToWatch_Menu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Mood_Menu = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        History_Menu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Genre_Menu = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        MenuContent = new javax.swing.JPanel();
        Home_Content = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        PlanToWatch_Content = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Mood_Content = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        History_Content = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SideBar.setBackground(new java.awt.Color(22, 22, 22));
        SideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Home_Menu.setBackground(new java.awt.Color(33, 78, 87));
        Home_Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Home_MenuMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Home");

        javax.swing.GroupLayout Home_MenuLayout = new javax.swing.GroupLayout(Home_Menu);
        Home_Menu.setLayout(Home_MenuLayout);
        Home_MenuLayout.setHorizontalGroup(
            Home_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Home_MenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Home_MenuLayout.setVerticalGroup(
            Home_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Home_MenuLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        SideBar.add(Home_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 300, -1));

        PlanToWatch_Menu.setBackground(new java.awt.Color(33, 78, 87));
        PlanToWatch_Menu.setPreferredSize(new java.awt.Dimension(300, 31));
        PlanToWatch_Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlanToWatch_MenuMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Plan to Watch");

        javax.swing.GroupLayout PlanToWatch_MenuLayout = new javax.swing.GroupLayout(PlanToWatch_Menu);
        PlanToWatch_Menu.setLayout(PlanToWatch_MenuLayout);
        PlanToWatch_MenuLayout.setHorizontalGroup(
            PlanToWatch_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PlanToWatch_MenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PlanToWatch_MenuLayout.setVerticalGroup(
            PlanToWatch_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PlanToWatch_MenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        SideBar.add(PlanToWatch_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, -1));

        Mood_Menu.setBackground(new java.awt.Color(37, 78, 87));
        Mood_Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Mood_MenuMouseClicked(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(37, 78, 87));
        jLabel10.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Mood");

        javax.swing.GroupLayout Mood_MenuLayout = new javax.swing.GroupLayout(Mood_Menu);
        Mood_Menu.setLayout(Mood_MenuLayout);
        Mood_MenuLayout.setHorizontalGroup(
            Mood_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        Mood_MenuLayout.setVerticalGroup(
            Mood_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        SideBar.add(Mood_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 300, -1));

        History_Menu.setBackground(new java.awt.Color(33, 78, 87));
        History_Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                History_MenuMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("History");

        javax.swing.GroupLayout History_MenuLayout = new javax.swing.GroupLayout(History_Menu);
        History_Menu.setLayout(History_MenuLayout);
        History_MenuLayout.setHorizontalGroup(
            History_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, History_MenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        History_MenuLayout.setVerticalGroup(
            History_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, History_MenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        SideBar.add(History_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 300, -1));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 50)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("CineHub");
        SideBar.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 110));

        Genre_Menu.setBackground(new java.awt.Color(33, 78, 87));
        Genre_Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Genre_MenuMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Genre");

        javax.swing.GroupLayout Genre_MenuLayout = new javax.swing.GroupLayout(Genre_Menu);
        Genre_Menu.setLayout(Genre_MenuLayout);
        Genre_MenuLayout.setHorizontalGroup(
            Genre_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Genre_MenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Genre_MenuLayout.setVerticalGroup(
            Genre_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Genre_MenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        SideBar.add(Genre_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, -1));

        getContentPane().add(SideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 650));

        MenuContent.setBackground(new java.awt.Color(38, 38, 38));
        MenuContent.setLayout(new java.awt.CardLayout());

        Home_Content.setBackground(new java.awt.Color(38, 38, 38));
        Home_Content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 50)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("HOMEPAGE :)");
        Home_Content.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        MenuContent.add(Home_Content, "card2");

        PlanToWatch_Content.setBackground(new java.awt.Color(38, 38, 38));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 50)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PLAN TO WATCH");

        javax.swing.GroupLayout PlanToWatch_ContentLayout = new javax.swing.GroupLayout(PlanToWatch_Content);
        PlanToWatch_Content.setLayout(PlanToWatch_ContentLayout);
        PlanToWatch_ContentLayout.setHorizontalGroup(
            PlanToWatch_ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PlanToWatch_ContentLayout.createSequentialGroup()
                .addContainerGap(259, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(224, 224, 224))
        );
        PlanToWatch_ContentLayout.setVerticalGroup(
            PlanToWatch_ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlanToWatch_ContentLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel6)
                .addContainerGap(563, Short.MAX_VALUE))
        );

        MenuContent.add(PlanToWatch_Content, "card2");

        Mood_Content.setBackground(new java.awt.Color(38, 38, 38));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 50)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("MOOD");

        javax.swing.GroupLayout Mood_ContentLayout = new javax.swing.GroupLayout(Mood_Content);
        Mood_Content.setLayout(Mood_ContentLayout);
        Mood_ContentLayout.setHorizontalGroup(
            Mood_ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Mood_ContentLayout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addComponent(jLabel7)
                .addContainerGap(335, Short.MAX_VALUE))
        );
        Mood_ContentLayout.setVerticalGroup(
            Mood_ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Mood_ContentLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel7)
                .addContainerGap(557, Short.MAX_VALUE))
        );

        MenuContent.add(Mood_Content, "card2");

        History_Content.setBackground(new java.awt.Color(38, 38, 38));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 50)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("HISTORY");

        javax.swing.GroupLayout History_ContentLayout = new javax.swing.GroupLayout(History_Content);
        History_Content.setLayout(History_ContentLayout);
        History_ContentLayout.setHorizontalGroup(
            History_ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(History_ContentLayout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addComponent(jLabel8)
                .addContainerGap(293, Short.MAX_VALUE))
        );
        History_ContentLayout.setVerticalGroup(
            History_ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(History_ContentLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel8)
                .addContainerGap(557, Short.MAX_VALUE))
        );

        MenuContent.add(History_Content, "card2");

        getContentPane().add(MenuContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 770, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Home_MenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home_MenuMouseClicked
        resetMenuColors();
        MenuContent.removeAll();
        MenuContent.repaint();
        MenuContent.revalidate();

        Film_Panel homePanel = new Film_Panel(); // Instantiate the HomePanel
        MenuContent.add(homePanel);
        Home_Menu.setBackground(new java.awt.Color(38, 38, 38));
        MenuContent.repaint();
        MenuContent.revalidate();
    }//GEN-LAST:event_Home_MenuMouseClicked

    private void PlanToWatch_MenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlanToWatch_MenuMouseClicked
        resetMenuColors();
        MenuContent.removeAll();
        MenuContent.repaint();
        MenuContent.revalidate();

        PlanToWatch_Panel plantowatch = new PlanToWatch_Panel(); // Instantiate the HomePanel
        MenuContent.add(plantowatch);
        PlanToWatch_Menu.setBackground(new java.awt.Color(38, 38, 38));
        MenuContent.repaint();
        MenuContent.revalidate();
    }//GEN-LAST:event_PlanToWatch_MenuMouseClicked

    private void Mood_MenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mood_MenuMouseClicked
        resetMenuColors();
        MenuContent.removeAll();
        MenuContent.repaint();
        MenuContent.revalidate();

        Mood_panel mood = new Mood_panel(); // Instantiate the HomePanel
        MenuContent.add(mood);
        Mood_Menu.setBackground(new java.awt.Color(38, 38, 38));
        MenuContent.repaint();
        MenuContent.revalidate();
    }//GEN-LAST:event_Mood_MenuMouseClicked

    private void History_MenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_History_MenuMouseClicked
        resetMenuColors();
        MenuContent.removeAll();
        MenuContent.repaint();
        MenuContent.revalidate();

        History_Panel history = new History_Panel(); // Instantiate the HomePanel
        MenuContent.add(history);
        History_Menu.setBackground(new java.awt.Color(38, 38, 38));
        MenuContent.repaint();
        MenuContent.revalidate();
    }//GEN-LAST:event_History_MenuMouseClicked

    private void Genre_MenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Genre_MenuMouseClicked
        resetMenuColors();
        MenuContent.removeAll();
        MenuContent.repaint();
        MenuContent.revalidate();

        Genre_panel genre = new Genre_panel(); // Instantiate the HomePanel
        MenuContent.add(genre);
        Genre_Menu.setBackground(new java.awt.Color(38, 38, 38));
        MenuContent.repaint();
        MenuContent.revalidate();
    }//GEN-LAST:event_Genre_MenuMouseClicked

    
    private void resetMenuColors() {
        Home_Menu.setBackground(new java.awt.Color(37, 78, 87));  // RGB values for #161616
        PlanToWatch_Menu.setBackground(new java.awt.Color(37, 78, 87));
        Mood_Menu.setBackground(new java.awt.Color(37, 78, 87));
        History_Menu.setBackground(new java.awt.Color(37, 78, 87));
        Genre_Menu.setBackground(new java.awt.Color(37, 78, 87));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Genre_Menu;
    private javax.swing.JPanel History_Content;
    private javax.swing.JPanel History_Menu;
    private javax.swing.JPanel Home_Content;
    private javax.swing.JPanel Home_Menu;
    private javax.swing.JPanel MenuContent;
    private javax.swing.JPanel Mood_Content;
    private javax.swing.JPanel Mood_Menu;
    private javax.swing.JPanel PlanToWatch_Content;
    private javax.swing.JPanel PlanToWatch_Menu;
    private javax.swing.JPanel SideBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
