/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Model.Mood;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Endri R
 */
public class Mood_panel extends javax.swing.JPanel {

    /**
     * Creates new form mood
     */
    public Mood_panel() {
        initComponents();
        displayFilm();
        Reset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        moodComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        MoodTable = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        OkBtn = new javax.swing.JButton();

        jPasswordField1.setText("jPasswordField1");

        setBackground(new java.awt.Color(38, 38, 38));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        moodComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sad", "Happy", "Tense", "Love", "Fear" }));
        moodComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moodComboBoxActionPerformed(evt);
            }
        });
        add(moodComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 120, 30));

        MoodTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Film ID", "Title", "Genre", "Duration", "Mood"
            }
        ));
        jScrollPane1.setViewportView(MoodTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 690, 350));

        jLabel15.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Mood");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 70, 30));

        OkBtn.setText("OK");
        OkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkBtnActionPerformed(evt);
            }
        });
        add(OkBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 50, 30));
    }// </editor-fold>//GEN-END:initComponents
    
    Connection Con = null;
    Statement St = null;
    ResultSet Rs = null;
    
    private void displayFilm() {
        try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cinehub", "root", "");
            St = Con.createStatement();
            Rs = St.executeQuery("select * from filmTable");
            MoodTable.setModel(DbUtils.resultSetToTableModel(Rs));
        }catch (SQLException e){
            e.printStackTrace();
        }
    }
    
    private void moodComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moodComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moodComboBoxActionPerformed

    private void OkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkBtnActionPerformed
            try {
            // Get the selected mood from the combo box
            String selectedMood = (String) moodComboBox.getSelectedItem();

            // Check if a mood is selected
            if (selectedMood != null) {
                // Construct the Mood object and set the moodType
                Mood mood = new Mood();
                mood.setMoodType(selectedMood);

                // Construct the SQL query with a WHERE clause based on the selected mood
                String query = "SELECT * FROM filmTable WHERE mood = '" + mood.getMoodType() + "'";

                // Establish database connection
                Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cinehub", "root", "");
                St = Con.createStatement();

                // Execute the query and update the table model
                Rs = St.executeQuery(query);
                MoodTable.setModel(DbUtils.resultSetToTableModel(Rs));
            } else {
                // Handle the case where no mood is selected
                System.out.println("Please select a mood");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_OkBtnActionPerformed

    public void Reset() {
        moodComboBox.setSelectedIndex(-1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable MoodTable;
    private javax.swing.JButton OkBtn;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> moodComboBox;
    // End of variables declaration//GEN-END:variables
}
